"""The published page — and the two rules the index checker structurally cannot carry.

`ADR-0004` (in the private index) puts one checker over all twelve published surfaces and
assertions in the repositories that have a page test. This repository had none, and S4 needs
one for a reason that is not convenience: **the checker reads a page's HTML and its CSS, and
cannot see this repository's artifacts.** So the two rules S4 is actually about are invisible
to it —

* *every figure the page prints is a figure a committed artifact prints* — it has nothing to
  compare against;
* *clause 2 binds where an artifact can source the tile* — its `clause_2_tiles` returns
  `n/a, §5.1 fallback applies` for any page with no tiles, before and after, because it
  cannot tell "exempt" from "nobody built tiles".

Everything else on this page — the ten tokens, the dark override, the wrapper, the eyebrow,
the card metadata, the system font stack, the separator — the checker does carry, and is not
restated here. Duplicating it in twelve places is the option `ADR-0004` rejected.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = (ROOT / "docs" / "index.html").read_text(encoding="utf-8")

#: What this page is allowed to quote. The three reports are committed and generated by
#: `examples/artifact_cost.py`, `examples/detector_evaluation.py`, `examples/drift_scenarios.py`.
#: `configs/config.yaml` is here because the page names a **declared** constant — the artifact
#: budget the promotion gate enforces — and `ADR-0012`'s declared-versus-measured distinction
#: admits that: it is committed, and a reader can find the line. A figure in none of these has
#: no provenance.
ARTIFACTS = (Path("reports/artifact_cost.md"), Path("reports/detector_evaluation.md"),
             Path("reports/drift_scenarios.md"), Path("configs/config.yaml"))

#: `0007` §5.0: a quotation is a digit sequence. The group separator is the page's typography —
#: clause 8 makes the page write `U+202F` where the artifact writes a comma — so both sides are
#: reduced to digits before comparing, and neither side's separator is part of the claim.
#: The separators a page may write where an artifact writes a comma.
_SEP_CHARS = "\u202f\u00a0\u2009 "
_SEPARATORS = str.maketrans(dict.fromkeys("," + _SEP_CHARS, ""))

#: Numbers a reader sees that are not results, cut out of the rendered text before tokenising
#: rather than excused afterwards. Each is a *shape* with a reason, never a value: a list of
#: allowed values goes stale in silence, which is what `0007` §5.0 sentence 2 is about.
_NOT_A_RESULT = (
    (r"\b(?:19|20)\d{2}-\d{2}-\d{2}\b", "a date is a fact about a run, not a cell of one"),
    (r"\b(?:19|20)\d{2}\b", "years"),
    (r"\b[AP]\d\b", "the portfolio's own ranking codes, A3 and P1"),
)


def _artifact_text() -> str:
    return "\n".join((ROOT / name).read_text(encoding="utf-8") for name in ARTIFACTS)


def _rendered_text() -> str:
    """What a reader sees: no stylesheet, no comments, no attributes, no tags.

    Comparing the **raw HTML** was the first attempt and it is hopeless — a URL's `223`, a
    hex literal's digits and an entity's `160` all read as claims, and the exemption list
    needed to silence them would be wider than the rule. `apply-scout`'s equivalent test
    reads rendered text for the same reason, and it is the reason.
    """
    text = re.sub(r"<(style|script)\b.*?</\1>", " ", PAGE, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"&#\d+;|&\w+;", " ", text)
    for pattern, _why in _NOT_A_RESULT:
        text = re.sub(pattern, " ", text)
    return text


_NUMBER = re.compile(r"\d[\d,.\u202f\u00a0\u2009 ]*\d|\d")


def _figures(text: str) -> set[str]:
    """Every number, reduced to its digits and decimal point."""
    return {token.translate(_SEPARATORS)
            for token in re.findall(_NUMBER, text)}


def test_every_figure_the_page_prints_is_one_a_committed_artifact_prints():
    """`ADR-0012`, and `0007` §5.0. The page quotes; it never retypes.

    Before S4 this page printed `728k rows/s` where `artifact_cost.md` prints `727,554` —
    a rounded number, which is a new number no reader can check. §5.0 sentence 2 is what
    makes that a violation rather than a style, and this is the only carrier that can see it:
    the index checker reads the page and the stylesheet and has no access to `reports/`.
    """
    unsourced = sorted(_figures(_rendered_text()) - _figures(_artifact_text()))
    assert not unsourced, (
        f"the page prints {unsourced}, which no committed artifact prints. Either the figure "
        "is a quotation and the artifact should be regenerated to produce it, or it is a new "
        "number and it does not belong on a page whose whole claim is that its figures are "
        "checkable."
    )


def test_the_exemptions_are_shapes_that_still_match_something():
    """A dead exemption is worse than none: it sits there widening the rule while covering
    nothing, and nobody notices because the suite stays green either way."""
    for pattern, why in _NOT_A_RESULT:
        assert re.search(pattern, PAGE), (
            f"the exemption for {why} matches nothing on this page, so it can only widen "
            f"what the check above accepts: {pattern!r}"
        )


def test_each_headline_tile_quotes_the_cell_it_summarises():
    """`0007` §5 clause 2, whose binding the index checker cannot carry — it grants §5.1's
    fallback to any page with no tiles and cannot see whether an artifact could source one.

    Asserted per tile against the cell, not in aggregate: four tiles all quoting the same
    number would satisfy a set comparison and say nothing.
    """
    cost = (ROOT / "reports" / "artifact_cost.md").read_text(encoding="utf-8")
    tiles = re.findall(r'<li class="kpi"><b>(.*?)</b><span>(.*?)</span>', PAGE, re.DOTALL)
    assert len(tiles) == 4, f"clause 2 asks for the tiles a reader scans first; found {len(tiles)}"
    for value, caption in tiles:
        digits = _figures(value)
        assert digits, f"the tile {caption!r} carries no figure"
        assert digits <= _figures(cost), (
            f"the tile {value!r} ({caption!r}) is not a cell of artifact_cost.md"
        )


def test_the_separator_and_the_code_ground_are_painted_apart():
    """The S3 defect, pinned in the repository it was loaded in.

    `#eef1f6` served two roles here — the table separator and `code`'s background — and a
    migration done by *value* maps both onto one token, leaves every name declared and
    resolvable, and ships a page both carriers report clean. The index checker's
    `1 usage roles` catches the separator half; **nothing catches the `code` half**, because
    a ground role in a ground property conforms whichever ground it names.

    Proved by the mutation it names: setting `code`'s background to `var(--border)` turns
    this red and leaves the checker reporting `clear`.
    """
    style = re.search(r"<style>(.*?)</style>", PAGE, re.DOTALL).group(1)
    separator = re.search(r"th,\s*td\s*\{[^}]*border-bottom:[^;]*var\(--([\w-]+)\)", style)
    ground = re.search(r"\bcode\s*\{[^}]*background:\s*var\(--([\w-]+)\)", style)
    assert separator, "no table separator painted with a token"
    assert ground, "no code background painted with a token"
    assert separator.group(1) == "border", (
        f"the table separator paints --{separator.group(1)}; six sibling pages write "
        "--border, and this page's own literal served that role"
    )
    assert ground.group(1) == "surface", (
        f"`code` paints --{ground.group(1)}; it is a ground, and --border is the edge"
    )


def test_the_page_names_its_own_measurement_and_points_at_the_sibling():
    """`0007` §6 clause 9's checkable half.

    This page and `car-price-ml` report the same two model families with the errors the other
    way round, and both are right: one scores a frozen holdout split, the other pooled
    out-of-fold MAE over 5-fold cross-validation on a de-duplicated corpus. What the clause
    forbids is a reader meeting both with no bridge.

    It also asserts the bridge carries **no figure from the other page**: those are that
    repository's cells, not this one's, and printing them would break the provenance rule
    above to satisfy this one.
    """
    prose = re.sub(r"<style>.*?</style>", " ", PAGE, flags=re.DOTALL)
    assert re.search(r"frozen holdout", prose, re.IGNORECASE), (
        "the page reports an MAE without naming the split it comes from"
    )
    assert "github.com/P0w3r223/car-price-ml" in prose, (
        "clause 9 asks this page to point at the other measurement, not only to name its own"
    )
    assert re.search(r"cross-validation", prose, re.IGNORECASE), (
        "the bridge names this measurement but not the sibling's, so a reader still meets "
        "two numbers and no reason they differ"
    )
    for foreign in ("8 612", "8,612", "8 798", "8,798", "111 018", "111,018"):
        assert foreign not in prose, (
            f"the page prints {foreign!r}, which is car-price-ml's cell and not this "
            "repository's — clause 9 asks for a bridge, not for the other page's figures"
        )
